name: Compile LaTeX projects

on:
  push:
    paths:
      - "Tareas/T3/**"
      - "Tareas/T4/**"
      - "Tareas/T5/**"
      - "Tareas/T6/**"
      - "Tareas/T7/**"
      - "Tareas/T8/**"

jobs:
  build-tarea-2:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T2
      tex_name: main
      out_name: "Tarea 1"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  Build-Tarea3:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T3
      tex_name: main
      out_name: "Tarea3"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  Build-Tarea4:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T4
      tex_name: main
      out_name: "Tarea4"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  Build-Tarea5:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T5
      tex_name: main
      out_name: "Tarea5"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  Build-Tarea6:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T6
      tex_name: main
      out_name: "Tarea6"
      send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  Build-Tarea7:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T7
      tex_name: main
      out_name: "Tarea7"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  Build-Tarea8:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T8
      tex_name: main
      out_name: "Tarea8"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit
